name: Pipeline to deploy site

# This determines when the action should run. 
on:
    schedule:
        - cron: '0 0 * * *' # Runs daily at midnight.
    merge_group: 
        branches: [ main ]
    workflow_dispatch:
    push:
        branches: [ dev ]
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ${{ secrets.AWS_REGION }}
    BUCKET_NAME: ${{secrets.BUCKET_NAME}}

jobs:
    build:
        runs-on: ubuntu-latest # The type of runner that the job will run on

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2 # This step checks out the repository under $GITHUB_WORKSPACE

            -   name: Set up Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '18' # Version number can be changed based on your needs

            -   name: Install dependencies
                run: npm install

            -   name: yarn install
                run: npm install -g yarn                            

            -   name: yarn build
                run: yarn build
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
        -   name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
                aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

        -   name: Cleanup S3 Bucket
            if: always() # Ensures cleanup step always runs
            run: aws s3 rm s3://${{env.BUCKET_NAME}} --recursive
                    
        -   name: Deploy to S3
            working-directory: ./build/
            run: aws s3 sync ./build s3://${{env.BUCKET_NAME}}


          